version: "3.4"
services:
  app:
    build:
      context: .
    command: jekyll serve -ws
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
